language: node_js
node_js:
 - "v11.13.0"
dist: trusty
sudo: false

branches:
 only:
 - master

cache:
 directories:
   - node_modules

install:
 - yarn install

script:
 - npm run-script build
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: master
